# Generated by Django 3.1.7 on 2021-05-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('altura', models.FloatField(blank=True, default=5.0, null=True)),
                ('largura', models.FloatField(blank=True, default=15.0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('comprimento', models.FloatField(blank=True, default=15.0, null=True)),
                ('espessura', models.FloatField(blank=True, default=0.2, null=True)),
                ('cobertura_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobertura_caixa', to='app.draw')),
                ('cobertura_fix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobertura_fix', to='app.draw')),
                ('cobertura_interna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobertura_interna', to='app.draw')),
                ('cobertura_tampa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobertura_tampa', to='app.draw')),
                ('draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draw', to='app.draw')),
                ('fix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix', to='app.draw')),
                ('fundo_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundo_caixa', to='app.draw')),
                ('laterais_maiores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laterais_maiores', to='app.draw')),
                ('laterais_menores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laterais_menores', to='app.draw')),
                ('lombada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lombada', to='app.draw')),
                ('tampa_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tampa_caixa', to='app.draw')),
                ('tampa_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tampa_fundo', to='app.draw')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
